import "dotenv/config";

export const NODE_ENV = process.env.NODE_ENV!,
  PORT = Number(process.env.PORT!),
  DATABASE_URL = process.env.DATABASE_URL!,
  BETTER_AUTH_URL = process.env.BETTER_AUTH_URL!,
  BETTER_AUTH_SECRET = process.env.BETTER_AUTH_SECRET!,
  RESEND_API_KEY = process.env.RESEND_API_KEY!,
  EMAIL_SENDING_DOMAIN = process.env.EMAIL_SENDING_DOMAIN!,
  FRONTEND_URL = process.env.FRONTEND_URL!,
  CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY!,
  CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET!,
  CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME!,
  UPSTASH_REDIS_REST_URL = process.env.UPSTASH_REDIS_REST_URL!,
  UPSTASH_REDIS_REST_TOKEN = process.env.UPSTASH_REDIS_REST_TOKEN!;
